# Use official Python image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Flask app files
COPY app.py score.py best_model.pkl tfidf_vectorizer.pkl .   

# Expose port
EXPOSE 5001

# Run the Flask app
CMD ["python", "app.py"]